Upgrade Xamarin.Firebase.Messaging to latest preview This gets us past `Java.Lang.NoClassDefFoundError: Failed resolution of: com.google.firebase.FirebaseApp`, which seems to be due to a firebase version mismatch.